### ISSUE TITLE
Issue in running

### ISSUE THREAD

**Issue by Midnight1938** [BashirHilaly/GPT-2-EssayWriter#2]
File "main.py", line 9, in <module>
    from transformers import AdamW, WarmUp, get_linear_schedule_with_warmup
ImportError: cannot import name 'WarmUp' from 'transformers' (/home/user/.local/lib/python3.8/site-packages/transformers/__init__.py)

**Comment by OG4EVER** [comment]
i have the same error 

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from transformers import AdamW, WarmUp, get_linear_schedule_with_warmup
ImportError: cannot import name 'WarmUp' from 'transformers' (/usr/local/lib/python3.8/dist-packages/transformers/__init__.py)\

Neither pytoh 2 or 3 will run it\
